server:
  port: 8080
  servlet:
    context-path: /electrical_management

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/electricity?useSSL=false&serverTimezone=UTC"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
jwt :
  signerKey : "KJ6yLDALgTbx2U4A9BasGYkzGW1ATVOqcZVllpe2aazpUi9X1Y4qiBGbr0exj/fC"

